/** Declaration file generated by dts-gen */

declare module "breezeconnect"{
  // eslint-disable-next-line require-jsdoc
  export class BreezeConnect {
    private params: { appKey: string };

    constructor(params: { appKey: string });
    generateSession(secretKey: string, apiSession: string): any;
  }
}


