/** Declaration file generated by dts-gen */

declare module "breezeconnect" {
  // eslint-disable-next-line require-jsdoc
  export class BreezeConnect {
    private params: { appKey: string };

    constructor(params: { appKey: string });

    generateSession(secretKey: string, sessionToken: string): Promise<void>;

    getCustomerDetails(sessionToken: string): Promise<any | undefined>;

    getFunds(): Promise<any | undefined>;

    placeOrder(params: {
      stockCode: string,
      exchangeCode: string,
      product: string,
      action: string,
      orderType: string,
      stoploss?: string,
      quantity: string,
      price: string,
      validity: string,
      validityDate?: string,
      disclosedQuantity?: string,
      expiryDate?: string,
      right?: string,
      strikePrice?: string,
      userRemark?: string,
      orderTypeFresh?: string,
      orderRateFresh?: string,
      settlementId?: string,
      orderSegmentCode?: string,
    }): Promise<any>;

    squareOff(params: {
      exchangeCode: string,
      product: string,
      stockCode: string,
      expiryDate: string,
      right: string,
      strikePrice: string,
      action: string,
      orderType: string,
      validity: string,
      stoploss: string,
      quantity: string,
      price: string,
      validityDate?: string,
      tradePassword: string,
      disclosedQuantity: string,
    }): Promise<any | undefined>;
  }
}


